/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.VinoVO;
import javax.swing.JOptionPane;

/**
 *
 * @author DAVID MOLINA
 */
public class InterfazFunciones extends javax.swing.JFrame {

    /**
     * Creates new form InterfazFunciones
     */
    public InterfazFunciones() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jCElementos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jTVinoSele = new javax.swing.JTextField();
        btnconfirmar = new javax.swing.JButton();
        btnMaridaje = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jlVino1 = new javax.swing.JLabel();
        jlVino2 = new javax.swing.JLabel();
        btnRadio1 = new javax.swing.JRadioButton();
        btnRadio2 = new javax.swing.JRadioButton();
        btnRadio3 = new javax.swing.JRadioButton();
        btnRadio4 = new javax.swing.JRadioButton();
        btnRadio5 = new javax.swing.JRadioButton();
        btnRadio6 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTmodificacion = new javax.swing.JTextField();
        btnVAM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(102, 0, 0));
        btnSalir.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("X");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 60, 50));

        jCElementos.setBackground(new java.awt.Color(153, 0, 0));
        jCElementos.setForeground(new java.awt.Color(255, 255, 255));
        jCElementos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Casa Productora", "Pais", "Color", "Edad", "Nivel de azucar", "Cepa de vinos", "Gas carbonico", "Crianza", "Metodo de elaboracion" }));
        jPanel2.add(jCElementos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 230, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html><body>Para modificar, eliminar o buscar un vino es necesario que ingreses el codigo del vino en el siguiente recueadro: <html><body>");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 120));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/Buscador.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 60, 60));

        jTVinoSele.setBackground(new java.awt.Color(102, 0, 0));
        jTVinoSele.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTVinoSele.setForeground(new java.awt.Color(255, 255, 255));
        jTVinoSele.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTVinoSele, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 80, 40));

        btnconfirmar.setBackground(new java.awt.Color(102, 0, 0));
        btnconfirmar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnconfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnconfirmar.setText("Confirmar");
        jPanel2.add(btnconfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 130, 40));

        btnMaridaje.setText("¿Maridaje?");
        jPanel2.add(btnMaridaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 100, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 160));

        titulo.setFont(new java.awt.Font("Brush Script MT", 1, 60)); // NOI18N
        titulo.setForeground(new java.awt.Color(102, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Wine APP");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 310, 70));

        jlVino1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlVino1.setForeground(new java.awt.Color(51, 0, 0));
        jlVino1.setText(".");
        jlVino1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jlVino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 350, 300));

        jlVino2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlVino2.setText(".");
        jlVino2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jlVino2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 310, 280));

        btnRadio1.setBackground(new java.awt.Color(204, 153, 0));
        btnRadio1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRadio1.setText("jRadioButton1");
        jPanel1.add(btnRadio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 220, 40));

        btnRadio2.setBackground(new java.awt.Color(204, 153, 0));
        btnRadio2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRadio2.setText("jRadioButton2");
        jPanel1.add(btnRadio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 220, 40));

        btnRadio3.setBackground(new java.awt.Color(204, 153, 0));
        btnRadio3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRadio3.setText("jRadioButton3");
        btnRadio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadio3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRadio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 220, 40));

        btnRadio4.setBackground(new java.awt.Color(204, 153, 0));
        btnRadio4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRadio4.setText("jRadioButton4");
        btnRadio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadio4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRadio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 210, 40));

        btnRadio5.setBackground(new java.awt.Color(204, 153, 0));
        btnRadio5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRadio5.setText("jRadioButton5");
        jPanel1.add(btnRadio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 210, 40));

        btnRadio6.setBackground(new java.awt.Color(204, 153, 0));
        btnRadio6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRadio6.setText("jRadioButton6");
        jPanel1.add(btnRadio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 210, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText( "<html><body>Completa o selecciona el dato oara completar la modificacion </body></html>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 330, 40));

        jTmodificacion.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.add(jTmodificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 240, 40));

        btnVAM.setBackground(new java.awt.Color(204, 153, 0));
        btnVAM.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnVAM.setForeground(new java.awt.Color(102, 0, 0));
        btnVAM.setText("Volver al menu");
        btnVAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVAMActionPerformed(evt);
            }
        });
        jPanel1.add(btnVAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 190, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRadio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRadio3ActionPerformed

    private void btnRadio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRadio4ActionPerformed

    private void btnVAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVAMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazFunciones().setVisible(true);
            }
        });
    }
    
    public void cambiotx(String paso, String vino){
        switch (paso){
            case "modificar":{
                btnRadio1.setVisible(false);
                btnRadio2.setVisible(false);
                btnRadio3.setVisible(false);
                btnRadio4.setVisible(false);
                btnRadio5.setVisible(false);
                btnRadio6.setVisible(false);
                jCElementos.setVisible(true);
                jTmodificacion.setVisible(false);
                jLabel1.setVisible(false);
                jlVino1.setVisible(false);
                jlVino2.setVisible(false);
                btnMaridaje.setVisible(false);
                btnconfirmar.setVisible(true);
                break;
            }
            case "buscar": {
                //Buscar vino
                btnRadio1.setVisible(false);
                btnRadio2.setVisible(false);
                btnRadio3.setVisible(false);
                btnRadio4.setVisible(false);
                btnRadio5.setVisible(false);
                btnRadio6.setVisible(false);
                jTmodificacion.setVisible(false);
                jLabel1.setVisible(false);
                jCElementos.setVisible(false);
                jlVino1.setVisible(false);
                jlVino2.setVisible(false);
                btnconfirmar.setVisible(true);
                btnMaridaje.setVisible(false);
                break;
            }
            case "buscarvino":{
                btnRadio1.setVisible(false);
                btnRadio2.setVisible(false);
                btnRadio3.setVisible(false);
                btnRadio4.setVisible(false);
                btnRadio5.setVisible(false);
                btnRadio6.setVisible(false);
                jCElementos.setVisible(false);
                jTmodificacion.setVisible(false);
                jLabel1.setVisible(false);
                jlVino1.setVisible(true);
                btnconfirmar.setVisible(true);
                jlVino1.setText("<html><body>"+vino+"<html><body>");
                btnMaridaje.setVisible(true);
                break;
            }
            case "vinoeliminado":{
                btnRadio1.setVisible(false);
                btnRadio2.setVisible(false);
                btnRadio3.setVisible(false);
                btnRadio4.setVisible(false);
                btnRadio5.setVisible(false);
                btnRadio6.setVisible(false);
                jCElementos.setVisible(false);
                jTmodificacion.setVisible(false);
                jLabel1.setVisible(false);
                jlVino1.setVisible(true);
                jlVino1.setText("<html><body>"+vino+"<html><body>");
                btnMaridaje.setVisible(false);
                break;
            }
            case "vinomodificado1":{
                btnRadio1.setVisible(false);
                btnRadio2.setVisible(false);
                btnRadio3.setVisible(false);
                btnRadio4.setVisible(false);
                btnRadio5.setVisible(false);
                btnRadio6.setVisible(false);
                jCElementos.setVisible(false);
                jTmodificacion.setVisible(false);
                jLabel1.setVisible(false);
                jlVino1.setVisible(true);
                jlVino1.setText("<html><body>"+vino+"<html><body>");
                btnMaridaje.setVisible(false);
                break;
            }
            case "vinomodificado2":{
                btnRadio1.setVisible(false);
                btnRadio2.setVisible(false);
                btnRadio3.setVisible(false);
                btnRadio4.setVisible(false);
                btnRadio5.setVisible(false);
                btnRadio6.setVisible(false);
                jCElementos.setVisible(false);
                jTmodificacion.setVisible(false);
                jLabel1.setVisible(false);
                jlVino2.setVisible(true);
                jlVino2.setText("<html><body>"+vino+"<html><body>");
                btnMaridaje.setVisible(false);
                break;
            }
            case "maridaje":{
                btnMaridaje.setVisible(false);
                jlVino2.setText("<html><body>"+vino+"<html><body>");
                jlVino2.setVisible(true);
            }
        }
    }
    
    public void cambios(String dato){
        System.out.println(dato);
        switch (dato){
            case "Nombre":{
                btnRadio1.setVisible(false);
                btnRadio2.setVisible(false);
                btnRadio3.setVisible(false);
                btnRadio4.setVisible(false);
                btnRadio5.setVisible(false);
                btnRadio6.setVisible(false);
                jTmodificacion.setVisible(true);
                jLabel1.setVisible(true);
                jlVino1.setVisible(false);
                jlVino2.setVisible(false); 
                btnconfirmar.setVisible(true);
                btnMaridaje.setVisible(false);
                break;
            }
            case "Casa Productora":{
                btnRadio1.setVisible(false);
                btnRadio2.setVisible(false);
                btnRadio3.setVisible(false);
                btnRadio4.setVisible(false);
                btnRadio5.setVisible(false);
                btnRadio6.setVisible(false);
                jCElementos.setVisible(true);
                jTmodificacion.setVisible(true);
                jLabel1.setVisible(true);
                jlVino1.setVisible(false);
                jlVino2.setVisible(false);
                btnMaridaje.setVisible(false);
                break;
            }
            case "Pais":{
                btnRadio1.setVisible(false);
                btnRadio2.setVisible(false);
                btnRadio3.setVisible(false);
                btnRadio4.setVisible(false);
                btnRadio5.setVisible(false);
                btnRadio6.setVisible(false);
                jCElementos.setVisible(true);
                jTmodificacion.setVisible(true);
                jLabel1.setVisible(true);
                jlVino1.setVisible(false);
                jlVino2.setVisible(false);
                btnMaridaje.setVisible(false);
                break;
            }
            
            case "Color": {
                btnRadio1.setVisible(true);
                btnRadio1.setText("Tinto");
                btnRadio2.setVisible(true);
                btnRadio2.setText("Blanco");
                btnRadio3.setVisible(true);
                btnRadio3.setText("Rosado");
                btnRadio4.setVisible(false);
                btnRadio5.setVisible(false);
                btnRadio6.setVisible(false);
                jTmodificacion.setVisible(false);
                jlVino1.setVisible(false);
                jlVino2.setVisible(false);
                btnMaridaje.setVisible(false);
                break;
            }
            case "Edad":{
                btnRadio1.setVisible(true);
                btnRadio1.setText("Joven");
                btnRadio2.setVisible(true);
                btnRadio2.setText("Crianza");
                btnRadio3.setVisible(true);
                btnRadio3.setText("Reserva");
                btnRadio4.setVisible(true);
                btnRadio4.setText("Gran reserva");
                btnRadio5.setVisible(false);
                btnRadio6.setVisible(false);
                jTmodificacion.setVisible(false);
                jlVino1.setVisible(false);
                jlVino2.setVisible(false);
                btnMaridaje.setVisible(false);
                break;
                
            }
            case "Nivel de azucar":{
                btnRadio1.setVisible(true);
                btnRadio1.setText("Seco");
                btnRadio2.setVisible(true);
                btnRadio2.setText("Semiseco");
                btnRadio3.setVisible(true);
                btnRadio3.setText("Abocados");
                btnRadio4.setVisible(true);
                btnRadio4.setText("Dulces");
                btnRadio5.setVisible(true);
                btnRadio5.setText("Muy dulces");
                btnRadio6.setVisible(false);
                jTmodificacion.setVisible(false);
                jlVino1.setVisible(false);
                jlVino2.setVisible(false);
                btnMaridaje.setVisible(false);
                break;
            }
            case "Cepa de vinos":{
                btnRadio1.setVisible(true);
                btnRadio1.setText("Cabernet Sauvignon");
                btnRadio2.setVisible(true);
                btnRadio2.setText("Pinot noir");
                btnRadio3.setVisible(true);
                btnRadio3.setText("Riesling");
                btnRadio4.setVisible(true);
                btnRadio4.setText("Merlot");
                btnRadio5.setVisible(true);
                btnRadio5.setText("Chardonnay");
                btnRadio6.setVisible(true);
                btnRadio6.setText("Sauvignon blanc");
                jTmodificacion.setVisible(false);
                jlVino1.setVisible(false);
                jlVino2.setVisible(false);
                btnMaridaje.setVisible(false);
                break; 
            }
            case "Gas carbonico":{
                btnRadio1.setVisible(true);
                btnRadio1.setText("Tranquilos");
                btnRadio2.setVisible(true);
                btnRadio2.setText("Aguja");
                btnRadio3.setVisible(true);
                btnRadio3.setText("Gasificada");
                btnRadio4.setVisible(true);
                btnRadio4.setText("Espumosos");
                btnRadio5.setVisible(true);
                btnRadio5.setText("Champenoise");
                btnRadio6.setVisible(true);
                btnRadio6.setText("Charmat");
                jTmodificacion.setVisible(false);
                jlVino1.setVisible(false);
                jlVino2.setVisible(false);
                btnMaridaje.setVisible(false);
                break;
            }
            case "Crianza":{
                btnRadio1.setVisible(true);
                btnRadio1.setText("Noble");
                btnRadio2.setVisible(true);
                btnRadio2.setText("Añejo");
                btnRadio3.setVisible(true);
                btnRadio3.setText("Viejo");
                btnRadio4.setVisible(false);
                btnRadio5.setVisible(false);
                btnRadio6.setVisible(false);
                jTmodificacion.setVisible(false);
                jlVino1.setVisible(false);
                jlVino2.setVisible(false);
                btnMaridaje.setVisible(false);
                break;
            }
            case "Metodo de elaboracion":{
                btnRadio1.setVisible(true);
                btnRadio1.setText("Maceración carbónica");
                btnRadio2.setVisible(true);
                btnRadio2.setText("Vendimia tardía");
                btnRadio3.setVisible(true);
                btnRadio3.setText("Vendimia seleccionada");
                btnRadio4.setVisible(true);
                btnRadio4.setText("Vinos especiales");
                btnRadio5.setVisible(false);
                btnRadio6.setVisible(false);
                jTmodificacion.setVisible(false);
                jLabel1.setVisible(false);
                jCElementos.setVisible(false);
                jlVino1.setVisible(false);
                jlVino2.setVisible(false);
                btnMaridaje.setVisible(false);
                break;
            }
        }
    }
    
    public void mensajeErrorLetras(String err){
         JOptionPane.showMessageDialog(null, err);
    }
    
    public void limpiardatos(){
        jTVinoSele.setText("");
        jTmodificacion.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnMaridaje;
    public javax.swing.JRadioButton btnRadio1;
    public javax.swing.JRadioButton btnRadio2;
    public javax.swing.JRadioButton btnRadio3;
    public javax.swing.JRadioButton btnRadio4;
    public javax.swing.JRadioButton btnRadio5;
    public javax.swing.JRadioButton btnRadio6;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnVAM;
    public javax.swing.JButton btnconfirmar;
    public javax.swing.JComboBox<String> jCElementos;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTVinoSele;
    public javax.swing.JTextField jTmodificacion;
    public javax.swing.JLabel jlVino1;
    public javax.swing.JLabel jlVino2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
